### ISSUE TITLE
[Bug]: horse armor on horse armor stand glitch picture available

### ISSUE THREAD

**Issue by BubbleTao225** [AlaharranHonor/SWEquestrianM#516] opened 2022-11-05 17:01 UTC
### What happened?

A bug happened!

### What should happen?

It should be normal. I updated the swem mod specifically and it did this 

### Mods

SWEM

### SWEM Version

Most recently uodated

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by BubbleTao225** [comment] 2022-11-05 17:01
![Uploading 4EFEFC6F-2CBC-4271-B31B-4FB0D64BE95B.jpeg…]()

**Comment by Mothfet** [comment] 2022-11-13 03:33
What specific mod versions are you running?

**Comment by MagnusHJensen** [comment] 2023-02-18 20:36
Duplicate of #509

**Closed by MagnusHJensen** 2023-02-18 20:36 UTC
Labels: bug
