### ISSUE TITLE
[Bug]: Basic Horse model

### ISSUE THREAD

**Issue by MChorseSWEM** [AlaharranHonor/SWEquestrianM#517] opened 2022-11-07 02:28 UTC
### What happened?

Ive downloaded all mods required, and the horses are still the basic-cubic ones. I dont know what to do?

### What should happen?

I would like to have the moded horses 
![image](https://user-images.githubusercontent.com/117614382/200213860-540556a5-52ed-4af0-a233-de7af4f2dfa3.png) 

### Mods

Geckolib-forge-1.16.5-3.0.92
Player-animation-lib-forge-0.3.5+1.16.5
swem-1.16.5-0.50
(i am also using optifine 1.16.5 for shaders)

### SWEM Version

swem-1.16.5-0.5.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by RileyCasper** [comment] 2022-11-10 12:28
This isn't a bug, SWEM Horses **DO NOT** spawn naturally, you have to give a vanilla horse a cantazarite potion. 
Find more information [https://wiki.swequestrian.com/books/star-worm-equestrian-mod/page/swem-horse](here).

**Comment by Mothfet** [comment] 2022-11-13 03:32
Closing report; not a bug.

**Closed** 2022-11-13 03:32 UTC
Labels: bug
