### ISSUE TITLE
[Bug]: I can't upload player animations

### ISSUE THREAD

**Issue by zosia33** [AlaharranHonor/SWEquestrianM#443] opened 2022-09-25 14:44 UTC
### What happened?

I just can't upload player animations

### What should happen?

It should upload normally

### Mods

all mods are working, but i can't play a game because of this one playeranimations

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Mothfet** [comment] 2022-09-25 18:22
I do not understand what "upload player animations" means. If all mods are working, then this is not a bug? Please provide more details.

**Comment by MagnusHJensen** [comment] 2022-10-01 13:30
If this is due to uploading the mod to your own mods folder, see our installation guide. 
https://wiki.swequestrian.com/books/star-worm-equestrian-mod/page/installing-mods

Closing this as invalid, please re-open if it's not due to installing mods.

**Closed by MagnusHJensen** 2022-10-01 13:30 UTC
Labels: bug
